title: stupid heng

name: stupid-heng's homepage
description:  I am liuheng. I think I'm not clever enough, so I add the stupid to active me to be more diligent. I completed my bachelor's degree in Faculty of Computer Science and Engineering Science at Chongqing University of Technology on July 1, 2015.
url: http://liuheng0111.github.io

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
